/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.pkg2;

import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class Intefaz_Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Intefaz_Grafica
     */
    ArrayList<CreacionArreglos> Nuevo = new ArrayList<CreacionArreglos>();
    ArrayList<Operaciones> ListaOperaciones = new ArrayList<Operaciones>();
   ArrayList<Ejercicio4> ListaPersonas = new ArrayList<Ejercicio4>();
    public Intefaz_Grafica() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        IngresarTamaño = new javax.swing.JTextField();
        Varianza = new javax.swing.JButton();
        Media = new javax.swing.JButton();
        Desviacion = new javax.swing.JButton();
        MostrarDesviacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextoInicial = new javax.swing.JTextField();
        ReemplazarCaracteres = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TamañoArreglo2 = new javax.swing.JTextField();
        Burbuja = new javax.swing.JButton();
        Merge = new javax.swing.JButton();
        TiempoInterseccion = new javax.swing.JButton();
        Arreglo2Ordenado = new javax.swing.JTextField();
        TiempoMerge = new javax.swing.JTextField();
        TiempoBurbuja = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ArregloOrdenado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IngresarNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        IngresarCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IngresarEdad = new javax.swing.JTextField();
        Merge2 = new javax.swing.JButton();
        Burbuja2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        GuardarPersona = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        MostrarMedia = new javax.swing.JTextField();
        MostrarVarianza = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TiempoSeleccion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaPersonas = new javax.swing.JTable();
        ArregloInicial = new java.awt.TextField();
        jLabel12 = new javax.swing.JLabel();
        CrearArreglo = new javax.swing.JButton();
        CrearArreglo2 = new javax.swing.JButton();
        ArregloInicial2 = new java.awt.TextField();
        jLabel13 = new javax.swing.JLabel();
        TextoReemplazado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 3), new java.awt.Dimension(0, 3), new java.awt.Dimension(32767, 3));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar tamaño del arreglo: ");

        IngresarTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarTamañoActionPerformed(evt);
            }
        });

        Varianza.setText("Varianza");
        Varianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarianzaActionPerformed(evt);
            }
        });

        Media.setText("Media");

        Desviacion.setText("Desviacion");

        MostrarDesviacion.setText("               ");

        jLabel2.setText("Ingrese un Texto:");

        TextoInicial.setText("                                              ");
        TextoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoInicialActionPerformed(evt);
            }
        });

        ReemplazarCaracteres.setText("Remplace caracteres");
        ReemplazarCaracteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReemplazarCaracteresActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el tamaño de arreglo doble :");

        TamañoArreglo2.setText("              ");
        TamañoArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamañoArreglo2ActionPerformed(evt);
            }
        });

        Burbuja.setText("Burbuja");

        Merge.setText("Merge");

        TiempoInterseccion.setText("Interseccion");

        Arreglo2Ordenado.setText("                             ");
        Arreglo2Ordenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arreglo2OrdenadoActionPerformed(evt);
            }
        });

        TiempoMerge.setText("               ");

        TiempoBurbuja.setText("               ");

        jTextField8.setText("             ");

        jLabel4.setText("Tiempo =");

        ArregloOrdenado.setText(" ");
        ArregloOrdenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArregloOrdenadoActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese su Nombre:");

        IngresarNombre.setText(" ");
        IngresarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese su Cedula:");

        jLabel7.setText("Ingrese su Edad: ");

        IngresarEdad.setText(" ");

        Merge2.setText("Merge");

        Burbuja2.setText("Burbuja");

        jLabel8.setText("Elija el tipo de ordenamiento:");

        GuardarPersona.setText("Guardar");
        GuardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPersonaActionPerformed(evt);
            }
        });

        jTextField13.setText(" ");

        MostrarMedia.setText(" ");

        MostrarVarianza.setText(" ");

        jLabel9.setText("Arreglo entero organizado: ");

        jLabel10.setText("Arreglo double ordenado: ");

        jLabel11.setText("Personas Ordenadas de menor a mayor: ");

        TiempoSeleccion.setText("Seleccion");

        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
        jScrollPane3.setViewportView(TablaPersonas);

        ArregloInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArregloInicialActionPerformed(evt);
            }
        });

        jLabel12.setText("Arreglo Inicial:");

        CrearArreglo.setText("Crear Arreglo");
        CrearArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArregloActionPerformed(evt);
            }
        });

        CrearArreglo2.setText("Crear Arreglo Doble");
        CrearArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArreglo2ActionPerformed(evt);
            }
        });

        ArregloInicial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArregloInicial2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Arreglo double Inicial: ");

        TextoReemplazado.setText("                                              ");

        jLabel14.setText("Cadena de caracteres Reemplazada: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Varianza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MostrarVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Media, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MostrarMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Desviacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MostrarDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ArregloInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArregloOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ArregloInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TamañoArreglo2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CrearArreglo2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(ReemplazarCaracteres))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TiempoMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(Merge, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(TiempoBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Burbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TiempoInterseccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TiempoSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoReemplazado, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Arreglo2Ordenado, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(IngresarTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CrearArreglo)
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(54, 54, 54)
                                .addComponent(Merge2)
                                .addGap(73, 73, 73)
                                .addComponent(Burbuja2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(IngresarEdad))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(IngresarCedula))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(GuardarPersona))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel10)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CrearArreglo))
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(ArregloInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ArregloOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Varianza)
                    .addComponent(Media, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desviacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MostrarVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MostrarMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MostrarDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReemplazarCaracteres)
                .addGap(8, 8, 8)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoReemplazado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TamañoArreglo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearArreglo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ArregloInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Burbuja)
                    .addComponent(Merge)
                    .addComponent(TiempoInterseccion)
                    .addComponent(TiempoSeleccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TiempoMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiempoBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Arreglo2Ordenado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IngresarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarPersona))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IngresarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Merge2)
                    .addComponent(Burbuja2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarTamañoActionPerformed
//        // TODO add your handling code here:                           
    }//GEN-LAST:event_IngresarTamañoActionPerformed

    private void VarianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarianzaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VarianzaActionPerformed

    private void ReemplazarCaracteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReemplazarCaracteresActionPerformed
        // TODO add your handling code here:
        
        TextoReemplazado.setText(" ");
        ReemplazarCaracteres NuevoReemplazar = new ReemplazarCaracteres();
        String cadena = TextoInicial.getText();
        NuevoReemplazar.ReemplazarCaracter(cadena);
        TextoReemplazado.setText(NuevoReemplazar.NuevaCadena);
    }//GEN-LAST:event_ReemplazarCaracteresActionPerformed

    private void IngresarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombreActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_IngresarNombreActionPerformed

    private void ArregloOrdenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArregloOrdenadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ArregloOrdenadoActionPerformed

    private void Arreglo2OrdenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arreglo2OrdenadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arreglo2OrdenadoActionPerformed

    private void CrearArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArregloActionPerformed
        // TODO add your handling code here:
        
        CreacionArreglos NuevoArreglo = new CreacionArreglos();
        int tamaño = Integer.parseInt(IngresarTamaño.getText());
        NuevoArreglo.CrearArregloInt(tamaño);
        int ArrayInterfaz[] = new int[tamaño];
        String ArrayInicial = " ";
         for (int i = 0; i < ArrayInterfaz.length; i++)
         {
         ArrayInterfaz[i] = NuevoArreglo.array[i];    
         }
         ArrayInicial = ArrayInterfaz.toString();
         ArregloInicial.setText(ArrayInicial);
         
        
        
        
    }//GEN-LAST:event_CrearArregloActionPerformed

    private void ArregloInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArregloInicialActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ArregloInicialActionPerformed

    private void CrearArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArreglo2ActionPerformed
        // TODO add your handling code here:
        ArregloInicial2.setText(" ");
        CreacionArreglos NuevoArreglo = new CreacionArreglos();
        int tamaño = Integer.parseInt(TamañoArreglo2.getText());
        NuevoArreglo.CrearArregloDoble(tamaño);
         
         
                
        
    }//GEN-LAST:event_CrearArreglo2ActionPerformed

    private void ArregloInicial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArregloInicial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArregloInicial2ActionPerformed

    private void TamañoArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamañoArreglo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TamañoArreglo2ActionPerformed

    private void GuardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPersonaActionPerformed
        // TODO add your handling code here:
        Ejercicio4 persona=new Ejercicio4(IngresarNombre.getText(),IngresarCedula.getText(),IngresarEdad.getText());
       ListaPersonas.add(persona);
       
       mostrar();
       
      IngresarNombre.setText("");
      IngresarCedula.setText("");
      IngresarEdad.setText("");
    }                                              
public void mostrar(){
    String matris [][] =new String[ListaPersonas.size()][3];
    for(int i=0;i<ListaPersonas.size();i++){
        matris[i][0]=ListaPersonas.get(i).getnombre();
         matris[i][1]=ListaPersonas.get(i).getcedula();
          matris[i][2]=ListaPersonas.get(i).getedad();
    }
    TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "Cedula", "Edad"
            }
        ));
    }//GEN-LAST:event_GuardarPersonaActionPerformed

    private void TextoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoInicialActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextoInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intefaz_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intefaz_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intefaz_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intefaz_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intefaz_Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Arreglo2Ordenado;
    private java.awt.TextField ArregloInicial;
    private java.awt.TextField ArregloInicial2;
    private javax.swing.JTextField ArregloOrdenado;
    private javax.swing.JButton Burbuja;
    private javax.swing.JButton Burbuja2;
    private javax.swing.JButton CrearArreglo;
    private javax.swing.JButton CrearArreglo2;
    private javax.swing.JButton Desviacion;
    private javax.swing.JButton GuardarPersona;
    private javax.swing.JTextField IngresarCedula;
    private javax.swing.JTextField IngresarEdad;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JTextField IngresarTamaño;
    private javax.swing.JButton Media;
    private javax.swing.JButton Merge;
    private javax.swing.JButton Merge2;
    private javax.swing.JTextField MostrarDesviacion;
    private javax.swing.JTextField MostrarMedia;
    private javax.swing.JTextField MostrarVarianza;
    private javax.swing.JButton ReemplazarCaracteres;
    private javax.swing.JTable TablaPersonas;
    private javax.swing.JTextField TamañoArreglo2;
    private javax.swing.JTextField TextoInicial;
    private javax.swing.JTextField TextoReemplazado;
    private javax.swing.JTextField TiempoBurbuja;
    private javax.swing.JButton TiempoInterseccion;
    private javax.swing.JTextField TiempoMerge;
    private javax.swing.JButton TiempoSeleccion;
    private javax.swing.JButton Varianza;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
